# Generated by Django 2.2.3 on 2019-10-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_auto_20190929_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanager.Item'),
        ),
    ]
