# Generated by Django 2.2.3 on 2019-10-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0004_auto_20191001_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='todolist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanager.ToDoList'),
        ),
    ]
